### ISSUE TITLE
Stuck on extension link step

### ISSUE THREAD

**Issue by lwshang** [zgqallen/jupyterlab-logout#1]
I successfuly built the extension but cannot link to jupyter. 
When I run the command `jupyter labextension link .`, it stuck and the console's final log shows as:

> [1/4] 🔍  Resolving packages...
> ⢀ @jupyterlab/logout@file:../extensions/jupyterlab-logout-1.0.0-047c3b6bf10ca58e84ef9942ba4262b34ede2a27.tgz

I'm using macOS 10.13.5. I installed nodejs 10.6.0 and npm 6.10.0 with MacPorts.
My python environment is from miniconda: python 3.6.5 and jupyterlab 0.32.1.

**Comment by zgqallen** [comment]
@lwshang , i don't has a MAC environment to reproduce issue, so i can't determine what is the issue. But could you verify if this is an issue by jupyter labextentsion link?  For example, could you install official  extension likes google-drive by command: jupyter labextension install @jupyterlab/google-drive?

**Comment by lwshang** [comment]
I switched back to the current stable nodejs 8.11.3 LTS and it works. I believe there is some compatible problems between jupyterlab and nodejs10 since I cannot install google-drive extension with nodejs10 either. The button really works. My suggestion is that you can make this extension a patch to Jupyterlab itself. Thanks for your help.

**Comment by zgqallen** [comment]
@lwshang Thanks for your try. I will close the issue.
